### ISSUE TITLE
discover_machine() fails on chrysalis compute nodes

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/mache#58] opened 2022-10-21 16:01 UTC
I was trying to launch zppy from a batch job on chrysalis (chained to my simulation job). Unfortunately, zppy failed because mache discover_machine() could not identify the machine. I assume it has to do with the hostname of compute nodes not being regognized by discover_machine():

https://github.com/E3SM-Project/mache/blob/d9b3bece9562be5ef3fde3ed847f1a143b27877a/mache/discover.py#L5-L37

The error in zppy was:

```
Traceback (most recent call last):
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.7.1_chrysalis/bin/zppy", line 10, in <module>
    sys.exit(main())
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.7.1_chrysalis/lib/python3.9/site-packages/zppy/__main__.py", line 79, in main
    machine_info = MachineInfo()
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.7.1_chrysalis/lib/python3.9/site-packages/mache/machine_info.py", line 75, in __init__
    raise ValueError('Unable to discover machine form host name')
ValueError: Unable to discover machine form host name

```

**Comment by forsyth2** [comment] 2022-10-21 16:23
> I assume it has to do with the hostname of compute nodes not being regognized by discover_machine()

Yes, if I recall correctly, Mache is meant to be run on log-in nodes.

**Comment by xylar** [comment] 2022-10-21 16:55
`discover_machine()` is not designed to succeed on compute nodes on any machine.

**Comment by xylar** [comment] 2022-10-21 17:01
> Yes, if I recall correctly, Mache is meant to be run on log-in nodes.

That's not true of mache on the whole, but it is true of `discover_machine()`.  If this is a `zppy` problem, you need to `discover_machine()` on the login node and then set an environment variable so you don't try to `discover_machine()` again on compute nodes.

**Comment by xylar** [comment] 2022-10-24 15:05
@golaz, unless you have a specific recommendation on how this can be improved, I'm going to close this.  It is the intended behavior that `discover_machine()` only works on login nodes.  Compute nodes typically have such generic names that it isn't possible to identify the machine by the host name.

**Comment by xylar** [comment] 2022-11-15 14:18
I closing this but am open to suggestions for how to address it if zppy fixes don't take care of the problem.

**Closed by xylar** 2022-11-15 14:18 UTC
Labels: bug
